packages:
  - apps/*
  - libs/*

nodeLinker: hoisted

allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': false
  '@scarf/scarf': false
  '@swc/core': true
  esbuild: true
  lmdb: false
  msgpackr-extract: false
  nx: true
  sqlite3: true
  unrs-resolver: false
